name: Monica Granbois
author: Monica Granbois
description: Explaining code to myself. 
highlighter: rouge
paginate: 10
twitter_username: mgranbois
github_username: MonicaG
url: "http://monicagranbois.com"
permalink: /blog/:categories/:title/
navbar_brand: Monica Granbois
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
