name: Monica Granbois
description: Explaining code to myself. 
highlighter: rouge
paginate: 5
disqusShortName: monicag
twitter_username: mgranbois
github_username: MonicaG
url: "http://monicagranbois.com"
permalink: /blog/:categories/:title
google_site_verification: ExTc2XTxRePfj38VQ7oJrNENFUTs7xQhS-1j1UlRKW4
bing_site_verification: DB6D94A115932508D6CD48BDADFE0AB1
navbar_brand: Explaining Code To Myself

gems:
  - jekyll-sitemap
  - jekyll-paginate





