name: Monica Granbois
author: Monica Granbois
description: Explaining code to myself. 
highlighter: rouge
paginate: 10
twitter_username: mgranbois
github_username: MonicaG
url: "http://monicagranbois.com"
tipjar_url: https://ko-fi.com/W7W4CXVBZ
permalink: /blog/:categories/:title/
navbar_brand: Monica Granbois
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
comments:
  repo: MonicaG/MonicaG.github.io
  label: blog comment
  theme: github-light
  issue-term: pathname
og:
  twitter_image: /favicon.png
  linkedin_image: /images/og/linkedin.jpg
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from