name: Explaining Code To Myself
description: Musings on programming.  I am currently focused on ios and Java 8.
highlighter: pygments
paginate: 5
disqusShortName: monicag
twitter_username: mgranbois
url: "http://monicagranbois.com"
permalink: /blog/:categories/:title



