name: Monica Granbois
description: Musings on programming.  I am currently focused on ios and Java 8.
highlighter: pygments
paginate: 5
disqusShortName: monicag
twitter_username: mgranbois
url: "http://monicagranbois.com"
permalink: /blog/:categories/:title
google_site_verification: ExTc2XTxRePfj38VQ7oJrNENFUTs7xQhS-1j1UlRKW4
navbar_brand: Explaining Code To Myself




